import { MaterialOption, ShippingOption } from '@/types';

export const AVAILABLE_MATERIALS: MaterialOption[] = [
  {
    id: 'sla_ultra_resin',
    name: 'เรซิน 8K ความละเอียดระดับ 25 ไมครอน',
    category: 'Resin',
    description: 'ผิวเรียบเนียนระดับกล้องจุลทรรศน์ ไร้รอยชั้นพิมพ์ เหมาะสำหรับฟิกเกอร์ตัวละคร งานสะสม และชิ้นงานประณีต',
    finish: 'ผิวด้านเนียนละเอียดพิเศษ หรือเคลือบเงา',
    colorHex: '#e2e8f0',
    densityGPerCm3: 1.18,
    pricePerGram: 0.14,
    durability: 4,
    detailLevel: 5,
    badge: 'ยอดนิยมสำหรับฟิกเกอร์',
    textureRoughness: 0.2,
    textureMetalness: 0.05,
  },
  {
    id: 'tough_pla_plus',
    name: 'อินดัสเทรียล แมตต์ PLA+',
    category: 'Filament',
    description: 'ไบโอโพลิเมอร์เป็นมิตรต่อสิ่งแวดล้อม ทนแรงกระแทกได้ดีเยี่ยม สีสันด้านสวยงาม ไม่บิดงอ',
    finish: 'ผิวซาตินด้านเรียบหรู',
    colorHex: '#38bdf8',
    densityGPerCm3: 1.24,
    pricePerGram: 0.06,
    durability: 4,
    detailLevel: 4,
    badge: 'คุ้มค่า & แข็งแรง',
    textureRoughness: 0.45,
    textureMetalness: 0.1,
  },
  {
    id: 'petg_carbon_fiber',
    name: 'คาร์บอนไฟเบอร์ PETG เสริมแกร่ง',
    category: 'Specialty',
    description: 'ผสมเส้นใยคาร์บอนแท้ ทนทานสูงมาก น้ำหนักเบาแต่แข็งแกร่ง ผิวสัมผัสแบบสเตลธ์แมตต์ลายคาร์บอน',
    finish: 'ผิวด้านลายคาร์บอนไฟเบอร์สเตลธ์',
    colorHex: '#1e293b',
    densityGPerCm3: 1.35,
    pricePerGram: 0.19,
    durability: 5,
    detailLevel: 4,
    badge: 'แข็งแกร่งทนทานสูงสุด',
    textureRoughness: 0.8,
    textureMetalness: 0.3,
  },
  {
    id: 'antique_cast_bronze',
    name: 'ทองสัมฤทธิ์หล่อโบราณแท้ (Bronze Metal)',
    category: 'Metal Composite',
    description: 'เนื้อโลหะทองสัมฤทธิ์แท้ 80% ขัดเงาด้วยมือและลงคราบสนิมเขียวโบราณ น้ำหนักแน่นทรงคุณค่าระดับงานพิพิธภัณฑ์',
    finish: 'โลหะทองสัมฤทธิ์ขัดเงาพาทินา',
    colorHex: '#d97706',
    densityGPerCm3: 3.90,
    pricePerGram: 0.38,
    durability: 5,
    detailLevel: 5,
    badge: 'เกรดพรีเมียมพิพิธภัณฑ์',
    textureRoughness: 0.25,
    textureMetalness: 0.9,
  },
  {
    id: 'translucent_glow_amber',
    name: 'เรซินคริสตัลเรืองแสง (Glow Crystal)',
    category: 'Specialty',
    description: 'เนื้อเรซินโปร่งแสงผสมผงฟอสฟอรัสคุณภาพสูง ส่องแสงเรืองรองนุ่มนวลในที่มืดหรือเมื่อกระทบแสงไฟ',
    finish: 'คริสตัลโปร่งแสงเรืองแสงสีอำพัน',
    colorHex: '#fbbf24',
    densityGPerCm3: 1.15,
    pricePerGram: 0.16,
    durability: 3,
    detailLevel: 4,
    badge: 'เรืองแสงในที่มืด',
    textureRoughness: 0.15,
    textureMetalness: 0.1,
    transmission: 0.7,
    emissive: '#d97706',
  },
  {
    id: 'full_color_sandstone',
    name: 'ฟูลคัลเลอร์ เซรามิกสีสมจริง (Full CMYK)',
    category: 'Specialty',
    description: 'พิมพ์สีสมบูรณ์แบบ CMYK ลงบนเนื้อผงเซรามิกทีละชั้น เหมาะสำหรับตัวละครเกมสีสดและงานสถาปัตยกรรม',
    finish: 'ผิวสัมผัสเซรามิกเนื้อละเอียด',
    colorHex: '#ec4899',
    densityGPerCm3: 1.60,
    pricePerGram: 0.26,
    durability: 3,
    detailLevel: 4,
    badge: 'พิมพ์สีสมจริง CMYK',
    textureRoughness: 0.5,
    textureMetalness: 0.05,
  }
];

export const AVAILABLE_SHIPPING_OPTIONS: ShippingOption[] = [
  {
    id: 'standard_14d',
    name: 'จัดส่งมาตรฐาน รับประกัน SLA 14 วัน',
    slaDays: 14,
    price: 9.99,
    description: 'พิมพ์ด้วยความแม่นยำ ขัดแต่งและอบแข็งด้วยมือ จัดส่งตรงถึงบ้านคุณภายใน 14 วันทำการ',
    guaranteeText: 'รับประกันคืนเงิน 100% เต็มจำนวน หากจัดส่งล่าช้าเกิน 14 วัน',
    badge: 'รับประกัน SLA 14 วัน',
  },
  {
    id: 'express_7d',
    name: 'จัดส่งด่วนพิเศษ Priority 7 วัน',
    slaDays: 7,
    price: 24.99,
    description: 'ลัดคิวเข้าเครื่องพิมพ์อุตสาหกรรมทันที พร้อมจัดส่งด่วนทางอากาศ Express Air',
    guaranteeText: 'รับประกันคืนเงิน 100% หากจัดส่งล่าช้าเกิน 7 วัน',
    badge: 'คิวด่วนพิเศษ 7 วัน',
  },
  {
    id: 'rush_3d',
    name: 'จัดส่งด่วน VIP Dedicated 3 วัน',
    slaDays: 3,
    price: 49.99,
    description: 'จัดสรรเครื่องพิมพ์เฉพาะงานของคุณทันทีที่ยืนยัน ตรวจสอบด้วยมือและส่งด้วยพนักงานขนส่งด่วนพิเศษ',
    guaranteeText: 'รับประกันคืนเงิน 100% หากจัดส่งล่าช้าเกิน 3 วัน',
    badge: 'VIP เร็วที่สุด 3 วัน',
  }
];
