export interface FreeSTLModel {
  id: string;
  title: string;
  titleTh: string;
  creator: string;
  creatorUrl?: string;
  source: 'Printables' | 'Thingiverse' | 'MakerWorld' | 'Thangs';
  sourceUrl: string;
  downloadUrl: string;
  directStlUrl: string;
  category: 
    | 'art_sculpture' 
    | 'gadgets_desk' 
    | 'home_organization' 
    | 'toys_games' 
    | 'cosplay_props' 
    | 'printer_tools' 
    | 'miniatures_rpg' 
    | 'mechanics_auto';
  categoryTh: string;
  categorySlug: string;
  license: 'CC BY 4.0' | 'CC0 Public Domain' | 'Creative Commons' | 'GPLv3' | 'Standard Digital License';
  fileFormat: string[]; // e.g. ['.STL', '.STEP', '.3MF']
  fileSizeMb: number;
  dimensionsCm: { width: number; depth: number; height: number };
  estimatedPrintHours: number;
  estimatedWeightGrams: number;
  recommendedMaterial: string;
  recommendedMaterialId: string;
  imageUrl: string;
  description: string;
  descriptionTh: string;
  tags: string[];
  likesCount: number;
  downloadsCount: number;
  featured?: boolean;
}

export interface STLCategory {
  id: string;
  name: string;
  nameTh: string;
  iconName: string;
  count: number;
  description: string;
}

export const STL_CATEGORIES: STLCategory[] = [
  {
    id: 'all',
    name: 'All Categories',
    nameTh: 'ทุกหมวดหมู่',
    iconName: 'Layers',
    count: 32,
    description: 'ไฟล์ STL ฟรีทั้งหมดจาก 4 เว็บไซต์ชั้นนำ',
  },
  {
    id: 'art_sculpture',
    name: 'Art & Sculptures',
    nameTh: 'งานศิลปะ & ประติมากรรม',
    iconName: 'Palette',
    count: 6,
    description: 'รูปปั้น ประติมากรรม งานศิลปะนามธรรม สแกน 3D พิพิธภัณฑ์',
  },
  {
    id: 'gadgets_desk',
    name: 'Gadgets & Desk Setup',
    nameTh: 'อุปกรณ์ไอที & จัดโต๊ะทำงาน',
    iconName: 'Monitor',
    count: 5,
    description: 'แท่นวางมือถือ ขาตั้งหูฟัง กล่องเก็บสายไฟ แท่นชาร์จ MagSafe',
  },
  {
    id: 'home_organization',
    name: 'Home & Organization',
    nameTh: 'ของแต่งบ้าน & กล่องจัดระเบียบ',
    iconName: 'Home',
    count: 5,
    description: 'กล่อง Gridfinity แจกันโมเดิร์น กระถางต้นไม้ ตะขอแขวนของ',
  },
  {
    id: 'toys_games',
    name: 'Toys, Games & Puzzles',
    nameTh: 'ของเล่น & ตัวต่อปริศนา',
    iconName: 'Gamepad2',
    count: 4,
    description: 'มังกรขยับข้อต่อ ฟิดเจ็ททอย กล่องลูกเต๋า เกมกระดาน',
  },
  {
    id: 'cosplay_props',
    name: 'Cosplay & Props',
    nameTh: 'คอสเพลย์ & อาวุธพร็อพ',
    iconName: 'Shield',
    count: 4,
    description: 'หน้ากาก หมวกเกราะ ดาบคอสเพลย์ ชิ้นส่วนสวมใส่เสมือนจริง',
  },
  {
    id: 'printer_tools',
    name: '3D Printer Upgrades & Tools',
    nameTh: 'อัปเกรดเครื่องพิมพ์ 3D & อุปกรณ์ช่าง',
    iconName: 'Wrench',
    count: 4,
    description: 'โมเดลทดสอบ Benchy กล่องเครื่องมือ ชิ้นส่วนอัปเกรด Bambu / Prusa',
  },
  {
    id: 'miniatures_rpg',
    name: 'Miniatures & Tabletop RPG',
    nameTh: 'ฟิกเกอร์ย่อส่วน & เกมกระดาน',
    iconName: 'Sparkles',
    count: 2,
    description: 'ตัวละคร D&D มอนสเตอร์ ฉากจำลอง Terrain ความละเอียดสูง',
  },
  {
    id: 'mechanics_auto',
    name: 'Mechanics & Engineering',
    nameTh: 'ชิ้นส่วนกลไก & วิศวกรรม',
    iconName: 'Cpu',
    count: 2,
    description: 'เฟืองทด ลูกปืนพิมพ์ได้ ชิ้นส่วนข้อต่อกลไก ชิ้นส่วน RC',
  },
];

export interface STLPlatform {
  id: 'all' | 'Printables' | 'Thingiverse' | 'MakerWorld' | 'Thangs';
  name: string;
  nameTh: string;
  url: string;
  searchUrl: (query: string) => string;
  badge: string;
  color: string;
  logo: string;
}

export const STL_PLATFORMS: STLPlatform[] = [
  {
    id: 'Printables',
    name: 'Printables by Prusa',
    nameTh: 'Printables (Prusa)',
    url: 'https://www.printables.com/model',
    searchUrl: (q) => `https://www.printables.com/search/models?q=${encodeURIComponent(q)}`,
    badge: 'คุณภาพโมเดลยอดเยี่ยม',
    color: '#fa6838',
    logo: 'https://www.printables.com/favicon.ico',
  },
  {
    id: 'MakerWorld',
    name: 'MakerWorld by Bambu Lab',
    nameTh: 'MakerWorld (Bambu Lab)',
    url: 'https://makerworld.com/en',
    searchUrl: (q) => `https://makerworld.com/en/search/models?keyword=${encodeURIComponent(q)}`,
    badge: 'กำลังมาแรงที่สุด 2026',
    color: '#00ae42',
    logo: 'https://makerworld.com/favicon.ico',
  },
  {
    id: 'Thingiverse',
    name: 'Thingiverse',
    nameTh: 'Thingiverse',
    url: 'https://www.thingiverse.com/',
    searchUrl: (q) => `https://www.thingiverse.com/search?q=${encodeURIComponent(q)}&page=1`,
    badge: 'คลังใหญ่ที่สุด 2.5M+',
    color: '#248bfb',
    logo: 'https://www.thingiverse.com/favicon.ico',
  },
  {
    id: 'Thangs',
    name: 'Thangs 3D',
    nameTh: 'Thangs 3D',
    url: 'https://thangs.com/',
    searchUrl: (q) => `https://thangs.com/search/${encodeURIComponent(q)}?scope=all`,
    badge: 'เสิร์ชเอนจิน 15M+ ทั่วโลก',
    color: '#8b5cf6',
    logo: 'https://thangs.com/favicon.ico',
  },
];

export const CURATED_FREE_STL_DATABASE: FreeSTLModel[] = [
  // 1. Art & Sculptures
  {
    id: 'stl-art-01',
    title: 'Venus de Milo Classical Museum Scan',
    titleTh: 'รูปปั้นเทพีวีนัสเดอไมโล (สแกนความละเอียดสูงระดับพิพิธภัณฑ์)',
    creator: 'Scan The World & Louvre Museum',
    creatorUrl: 'https://www.printables.com/@ScanTheWorld',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com/model/3160-venus-de-milo',
    downloadUrl: 'https://www.printables.com/model/3160-venus-de-milo',
    directStlUrl: 'https://www.printables.com/model/3160-venus-de-milo',
    category: 'art_sculpture',
    categoryTh: 'งานศิลปะ & ประติมากรรม',
    categorySlug: 'art_sculpture',
    license: 'CC0 Public Domain',
    fileFormat: ['.STL', '.OBJ', '.3MF'],
    fileSizeMb: 42.5,
    dimensionsCm: { width: 9.5, depth: 8.2, height: 22.0 },
    estimatedPrintHours: 11.5,
    estimatedWeightGrams: 185,
    recommendedMaterial: 'เรซิน 8K ความละเอียดสูง (ผิวสัมผัสเรียบเนียนระดับหินอ่อน)',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=800&q=80',
    description: 'Ultra-high resolution 3D scan of the iconic ancient Greek sculpture Venus de Milo from the Louvre Museum in Paris. Manifold watertight mesh optimized for SLA and FDM 3D printing.',
    descriptionTh: 'ไฟล์สแกน 3 มิติความละเอียดระดับมาสเตอร์พีซของรูปปั้นเทพีวีนัสแห่งเกาะไมลอส จากพิพิธภัณฑ์ลูฟวร์ ประเทศฝรั่งเศส เมชปิดสนิทไม่มีรูรั่ว เหมาะกับการพิมพ์ด้วยเรซิน 8K หรือทองสัมฤทธิ์หล่อ',
    tags: ['Louvre', 'Sculpture', 'Classic', 'Art', 'Museum', 'ScanTheWorld', 'Statue'],
    likesCount: 14200,
    downloadsCount: 52400,
    featured: true,
  },
  {
    id: 'stl-art-02',
    title: 'Parametric Voronoi Spiral Twisted Vase',
    titleTh: 'แจกันเกลียวพารามิเตอร์ Voronoi โมเดิร์น',
    creator: 'BigBrain3D',
    creatorUrl: 'https://makerworld.com/en/@BigBrain3D',
    source: 'MakerWorld',
    sourceUrl: 'https://makerworld.com/en/models/48291',
    downloadUrl: 'https://makerworld.com/en/models/48291',
    directStlUrl: 'https://makerworld.com/en/models/48291',
    category: 'art_sculpture',
    categoryTh: 'งานศิลปะ & ประติมากรรม',
    categorySlug: 'art_sculpture',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP', '.3MF'],
    fileSizeMb: 18.2,
    dimensionsCm: { width: 12.0, depth: 12.0, height: 20.0 },
    estimatedPrintHours: 7.0,
    estimatedWeightGrams: 140,
    recommendedMaterial: 'เรซินใสออพติคอล Crystal Clear หรือเส้น Silk PLA',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80',
    description: 'Generative organic vase with parametric Voronoi spiral cellular walls. Seamless watertight interior with outer aesthetic mesh.',
    descriptionTh: 'แจกันศิลปะแบบ Generative ดีไซน์ผนังตาข่ายเซลล์ Voronoi แบบเกลียวบิด พิมพ์ออกมาเป็นของแต่งบ้านหรือแจกันดอกไม้ระดับโมเดิร์นลักชัวรี่',
    tags: ['Vase', 'Voronoi', 'Parametric', 'HomeDecor', 'Spiral', 'Art'],
    likesCount: 9800,
    downloadsCount: 38100,
    featured: true,
  },
  {
    id: 'stl-art-03',
    title: 'The Thinker (Le Penseur) by Rodin',
    titleTh: 'รูปปั้นคนครุ่นคิด (The Thinker) ของออกุสต์ โรแดง',
    creator: 'CosmoWenman',
    creatorUrl: 'https://www.thingiverse.com/cosmowenman',
    source: 'Thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:216407',
    downloadUrl: 'https://www.thingiverse.com/thing:216407',
    directStlUrl: 'https://www.thingiverse.com/thing:216407',
    category: 'art_sculpture',
    categoryTh: 'งานศิลปะ & ประติมากรรม',
    categorySlug: 'art_sculpture',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.OBJ'],
    fileSizeMb: 35.0,
    dimensionsCm: { width: 10.0, depth: 13.0, height: 18.0 },
    estimatedPrintHours: 9.5,
    estimatedWeightGrams: 210,
    recommendedMaterial: 'ทองสัมฤทธิ์หล่อแท้ 80% (Antique Cast Bronze)',
    recommendedMaterialId: 'antique_cast_bronze',
    imageUrl: 'https://images.unsplash.com/photo-1569783727508-329813c9df92?auto=format&fit=crop&w=800&q=80',
    description: 'Museum grade photogrammetry capture of Auguste Rodin classic bronze masterwork.',
    descriptionTh: 'ประติมากรรมระดับมาสเตอร์พีซอันดับ 1 ของโลก ถอดแบบจากรูปหล่อทองสัมฤทธิ์จริงของโรแดง เหมาะอย่างยิ่งกับการหล่อด้วยโลหะบรอนซ์',
    tags: ['Thinker', 'Rodin', 'Bronze', 'Statue', 'Art', 'Classic'],
    likesCount: 18500,
    downloadsCount: 68000,
  },

  // 2. Gadgets & Desk Setup
  {
    id: 'stl-gadget-01',
    title: 'Universal Foldable Heavy Phone & Tablet Stand',
    titleTh: 'ขาตั้งมือถือและแท็บเล็ตพับได้ ปรับระดับองศาได้',
    creator: 'gcreate',
    creatorUrl: 'https://www.thingiverse.com/thing:2120591',
    source: 'Thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:2120591',
    downloadUrl: 'https://www.thingiverse.com/thing:2120591',
    directStlUrl: 'https://www.thingiverse.com/thing:2120591',
    category: 'gadgets_desk',
    categoryTh: 'อุปกรณ์ไอที & จัดโต๊ะทำงาน',
    categorySlug: 'gadgets_desk',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP'],
    fileSizeMb: 4.8,
    dimensionsCm: { width: 8.0, depth: 10.0, height: 3.5 },
    estimatedPrintHours: 3.5,
    estimatedWeightGrams: 65,
    recommendedMaterial: 'คาร์บอนไฟเบอร์ PETG ผิวด้านสเตลธ์ แข็งแรงทนทานสูง',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=800&q=80',
    description: 'Print-in-place foldable phone and tablet stand with multiple viewing angles and cable cutout.',
    descriptionTh: 'ขาตั้งสมาร์ทโฟนและไอแพดแบบพับได้ พกพาสะดวก มีช่องเสียบสายชาร์จและตัวล็อกองศาแน่นหนา ไม่ล้ม',
    tags: ['PhoneStand', 'Tablet', 'DeskSetup', 'PrintInPlace', 'Functional', 'Gadget'],
    likesCount: 32000,
    downloadsCount: 145000,
    featured: true,
  },
  {
    id: 'stl-gadget-02',
    title: 'Minimalist Apple Watch & MagSafe 2-in-1 Charging Dock',
    titleTh: 'แท่นชาร์จไร้สาย MagSafe & Apple Watch มินิมอล',
    creator: 'Designcraft3D',
    creatorUrl: 'https://makerworld.com/en/@Designcraft3D',
    source: 'MakerWorld',
    sourceUrl: 'https://makerworld.com/en/models/62910',
    downloadUrl: 'https://makerworld.com/en/models/62910',
    directStlUrl: 'https://makerworld.com/en/models/62910',
    category: 'gadgets_desk',
    categoryTh: 'อุปกรณ์ไอที & จัดโต๊ะทำงาน',
    categorySlug: 'gadgets_desk',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP', '.3MF'],
    fileSizeMb: 6.2,
    dimensionsCm: { width: 9.0, depth: 9.0, height: 11.0 },
    estimatedPrintHours: 4.0,
    estimatedWeightGrams: 85,
    recommendedMaterial: 'Industrial Matte PLA+ หรือ PETG Carbon Fiber',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=800&q=80',
    description: 'Clean modern desk charging dock with built-in channels for authentic Apple MagSafe and Watch pucks.',
    descriptionTh: 'แท่นชาร์จหัวเตียงและโต๊ะทำงานดีไซน์มินิมอล มีร่องซ่อนสายไฟพอดีกับที่ชาร์จ MagSafe แท้ และ Apple Watch',
    tags: ['MagSafe', 'AppleWatch', 'ChargingDock', 'Desk', 'Minimalist'],
    likesCount: 11400,
    downloadsCount: 42000,
  },
  {
    id: 'stl-gadget-03',
    title: 'Ergonomic Desk Headphone Stand with Cable Organizer',
    titleTh: 'ขาตั้งหูฟังเกมมิ่งทรงแอร์โรไดนามิก พร้อมที่เก็บสาย',
    creator: 'MakerBot',
    creatorUrl: 'https://thangs.com/designer/MakerBot',
    source: 'Thangs',
    sourceUrl: 'https://thangs.com/m/38914',
    downloadUrl: 'https://thangs.com/m/38914',
    directStlUrl: 'https://thangs.com/m/38914',
    category: 'gadgets_desk',
    categoryTh: 'อุปกรณ์ไอที & จัดโต๊ะทำงาน',
    categorySlug: 'gadgets_desk',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP'],
    fileSizeMb: 9.5,
    dimensionsCm: { width: 14.0, depth: 14.0, height: 26.0 },
    estimatedPrintHours: 8.0,
    estimatedWeightGrams: 190,
    recommendedMaterial: 'คาร์บอนไฟเบอร์ PETG รับน้ำหนักหูฟังฟูลไซส์ได้สบาย',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Sturdy geometric headphone stand designed to prevent headband sagging and hold heavy gaming headsets.',
    descriptionTh: 'ขาตั้งหูฟังทรงโค้งรับสรีระแบนด์ ไม่ทำให้ฟองน้ำหูฟังเสียทรง ฐานกว้างมั่นคงพร้อมช่องพันเก็บสายหูฟัง',
    tags: ['Headphone', 'Gaming', 'DeskSetup', 'Audio', 'Stand'],
    likesCount: 16800,
    downloadsCount: 61000,
  },

  // 3. Home & Organization
  {
    id: 'stl-home-01',
    title: 'Gridfinity Master Storage System Modules',
    titleTh: 'ชุดกล่องจัดระเบียบ Gridfinity ลิเนียร์โมดูลาร์',
    creator: 'Zack Freedman (Gridfinity Spec)',
    creatorUrl: 'https://www.printables.com/@ZackFreedman',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com/model/174346-gridfinity-baseplates-and-bins',
    downloadUrl: 'https://www.printables.com/model/174346-gridfinity-baseplates-and-bins',
    directStlUrl: 'https://www.printables.com/model/174346-gridfinity-baseplates-and-bins',
    category: 'home_organization',
    categoryTh: 'ของแต่งบ้าน & กล่องจัดระเบียบ',
    categorySlug: 'home_organization',
    license: 'CC0 Public Domain',
    fileFormat: ['.STL', '.STEP', '.3MF'],
    fileSizeMb: 15.0,
    dimensionsCm: { width: 12.6, depth: 12.6, height: 6.0 },
    estimatedPrintHours: 5.0,
    estimatedWeightGrams: 110,
    recommendedMaterial: 'Industrial Matte PLA+ หรือ PETG',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    description: 'The world-famous open source Gridfinity workshop and desk organization system. Stackable, magnetic, and modular.',
    descriptionTh: 'ระบบกล่องจัดระเบียบลิ้นชักและโต๊ะช่าง Gridfinity ที่โด่งดังที่สุดในโลก ซ้อนได้ วางแม่เหล็กได้ พอดีทุกช่อง',
    tags: ['Gridfinity', 'Organizer', 'Toolbox', 'Modular', 'ZackFreedman', 'DeskStorage'],
    likesCount: 45000,
    downloadsCount: 220000,
    featured: true,
  },
  {
    id: 'stl-home-02',
    title: 'Self-Watering Geometric Succulent Planter Pot',
    titleTh: 'กระถางต้นไม้แคคตัสรดน้ำอัตโนมัติ ทรงเรขาคณิต',
    creator: 'ParallelGoods',
    creatorUrl: 'https://www.thingiverse.com/thing:903411',
    source: 'Thingiverse',
    sourceUrl: 'https://www.thingiverse.com/thing:903411',
    downloadUrl: 'https://www.thingiverse.com/thing:903411',
    directStlUrl: 'https://www.thingiverse.com/thing:903411',
    category: 'home_organization',
    categoryTh: 'ของแต่งบ้าน & กล่องจัดระเบียบ',
    categorySlug: 'home_organization',
    license: 'CC BY 4.0',
    fileFormat: ['.STL'],
    fileSizeMb: 7.2,
    dimensionsCm: { width: 11.0, depth: 11.0, height: 10.5 },
    estimatedPrintHours: 5.5,
    estimatedWeightGrams: 120,
    recommendedMaterial: 'PETG กันน้ำได้ดี หรือเรซินใสสำหรับแทงก์น้ำ',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80',
    description: 'Two-part self-watering planter pot with reservoir basin and moisture wicking inner basket.',
    descriptionTh: 'กระถางต้นไม้ 2 ชั้น มีแทงก์กักเก็บน้ำด้านล่าง ดึงความชื้นขึ้นมาเลี้ยงรากอัตโนมัติ ไม่ต้องรดน้ำทุกวัน',
    tags: ['Planter', 'SelfWatering', 'Succulent', 'Plant', 'Home', 'Garden'],
    likesCount: 28000,
    downloadsCount: 110000,
  },

  // 4. Toys, Games & Puzzles
  {
    id: 'stl-toy-01',
    title: 'Articulated Flexible Crystal Dragon (Print-in-Place)',
    titleTh: 'มังกรผลึกคริสตัลขยับข้อต่อได้รอบทิศ (ไม่ต้องประกอบ)',
    creator: 'Cinderwing3D',
    creatorUrl: 'https://thangs.com/designer/Cinderwing3D',
    source: 'Thangs',
    sourceUrl: 'https://thangs.com/m/321894',
    downloadUrl: 'https://thangs.com/m/321894',
    directStlUrl: 'https://thangs.com/m/321894',
    category: 'toys_games',
    categoryTh: 'ของเล่น & ตัวต่อปริศนา',
    categorySlug: 'toys_games',
    license: 'Creative Commons',
    fileFormat: ['.STL', '.3MF'],
    fileSizeMb: 24.0,
    dimensionsCm: { width: 18.0, depth: 18.0, height: 4.5 },
    estimatedPrintHours: 12.0,
    estimatedWeightGrams: 160,
    recommendedMaterial: 'เรซิน 8K Ultra-Detail หรือ Dual-Color Silk PLA',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    description: 'Extremely popular print-in-place articulated dragon with interlocking joints and crystalline scale texture.',
    descriptionTh: 'มังกรขยับข้อต่อได้สมจริง ลำตัวพริ้วไหว ข้อต่อเชื่อมกันตั้งแต่ตอนพิมพ์เสร็จโดยไม่ต้องประกอบหรือใช้น็อต',
    tags: ['Dragon', 'Articulated', 'PrintInPlace', 'Flexi', 'Toy', 'Cinderwing3D'],
    likesCount: 88000,
    downloadsCount: 390000,
    featured: true,
  },
  {
    id: 'stl-toy-02',
    title: 'D20 Polyhedral Dice Tower with Dragon Castle Staircase',
    titleTh: 'หอคอยทอยลูกเต๋า D&D ลายปราสาทมังกรโบราณ',
    creator: 'ArsMakers',
    creatorUrl: 'https://www.printables.com/@ArsMakers',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com/model/89201-dice-tower-castle',
    downloadUrl: 'https://www.printables.com/model/89201-dice-tower-castle',
    directStlUrl: 'https://www.printables.com/model/89201-dice-tower-castle',
    category: 'toys_games',
    categoryTh: 'ของเล่น & ตัวต่อปริศนา',
    categorySlug: 'toys_games',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP'],
    fileSizeMb: 38.0,
    dimensionsCm: { width: 14.0, depth: 18.0, height: 21.0 },
    estimatedPrintHours: 14.0,
    estimatedWeightGrams: 280,
    recommendedMaterial: 'หินอ่อนเรซิน หรือทองสัมฤทธิ์หล่อแท้',
    recommendedMaterialId: 'antique_cast_bronze',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    description: 'Castle dice tower with spiraling staircase and walled dice rolling tray. Perfect for D&D and tabletop RPG sessions.',
    descriptionTh: 'หอคอยทอยลูกเต๋าทรงปราสาทยุคกลาง มีบันไดเวียนด้านในและถาดรับลูกเต๋าหน้าประตู เหมาะสำหรับบอร์ดเกมและ D&D',
    tags: ['DND', 'DiceTower', 'Tabletop', 'RPG', 'Castle', 'BoardGame'],
    likesCount: 22400,
    downloadsCount: 78000,
  },

  // 5. Cosplay & Props
  {
    id: 'stl-cosplay-01',
    title: 'Cyberpunk Oni Demon Samurai Helmet Mask (Full Scale 1:1)',
    titleTh: 'หน้ากากนักรบปีศาจไซเบอร์พังค์ โอนิ (สเกลจริง 1:1 สวมใส่ได้)',
    creator: 'CyberArtisan',
    creatorUrl: 'https://makerworld.com/en/@CyberArtisan',
    source: 'MakerWorld',
    sourceUrl: 'https://makerworld.com/en/models/99120',
    downloadUrl: 'https://makerworld.com/en/models/99120',
    directStlUrl: 'https://makerworld.com/en/models/99120',
    category: 'cosplay_props',
    categoryTh: 'คอสเพลย์ & อาวุธพร็อพ',
    categorySlug: 'cosplay_props',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.OBJ', '.STEP'],
    fileSizeMb: 58.0,
    dimensionsCm: { width: 18.0, depth: 16.0, height: 22.0 },
    estimatedPrintHours: 18.0,
    estimatedWeightGrams: 320,
    recommendedMaterial: 'คาร์บอนไฟเบอร์ PETG หรือเรซินทนแรงกระแทกสูง (สวมใส่ได้จริง)',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    description: 'Full wearable scale 1:1 cyberpunk samurai mask with strap mounting points, breather tube channels, and aggressive horns.',
    descriptionTh: 'หน้ากากไซเบอร์พังค์สเกล 1:1 ขนาดสวมใส่ได้จริง มีช่องใส่สายรัดศีรษะและช่องระบายอากาศ พร้อมเขาโอนิเหลี่ยมเรขาคณิต',
    tags: ['Cyberpunk', 'Oni', 'Mask', 'Cosplay', 'Samurai', 'Wearable', 'Helmet'],
    likesCount: 38000,
    downloadsCount: 94000,
    featured: true,
  },
  {
    id: 'stl-cosplay-02',
    title: 'Mandalorian Beskar Helmet (Screen Accurate 1:1)',
    titleTh: 'หมวกเกราะแมนดาลอเรียน เบสการ์ (สเกลเท่าของจริง 1:1)',
    creator: 'GalacticArmory',
    creatorUrl: 'https://www.printables.com/@GalacticArmory',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com/model/49102-mandalorian-helmet',
    downloadUrl: 'https://www.printables.com/model/49102-mandalorian-helmet',
    directStlUrl: 'https://www.printables.com/model/49102-mandalorian-helmet',
    category: 'cosplay_props',
    categoryTh: 'คอสเพลย์ & อาวุธพร็อพ',
    categorySlug: 'cosplay_props',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.3MF'],
    fileSizeMb: 75.0,
    dimensionsCm: { width: 24.0, depth: 26.0, height: 28.0 },
    estimatedPrintHours: 28.0,
    estimatedWeightGrams: 650,
    recommendedMaterial: 'PETG Carbon Fiber หรือขัดพ่นสี Chrome Silver',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?auto=format&fit=crop&w=800&q=80',
    description: 'Screen accurate one-piece Mandalorian helmet ready for visor install and cosplay.',
    descriptionTh: 'หมวกเกราะยอดฮิต สเกล 1:1 ถอดแบบจากซีรีส์ พร้อมร่องใส่แผ่นบังตา T-visor ด้านหน้า',
    tags: ['Mandalorian', 'StarWars', 'Helmet', 'Cosplay', 'Prop', 'Beskar'],
    likesCount: 54000,
    downloadsCount: 180000,
  },

  // 6. 3D Printer Upgrades & Tools
  {
    id: 'stl-tool-01',
    title: '3DBenchy - The Jolly 3D Printing Torture Test Benchmark',
    titleTh: 'เรือเบนชี่ 3DBenchy (โมเดลทดสอบความแม่นยำมาตรฐานโลก)',
    creator: 'Creative Tools',
    creatorUrl: 'https://www.3dbenchy.com',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com/model/3161-3dbenchy-the-jolly-3d-printing-torture-test',
    downloadUrl: 'https://www.printables.com/model/3161-3dbenchy-the-jolly-3d-printing-torture-test',
    directStlUrl: 'https://www.printables.com/model/3161-3dbenchy-the-jolly-3d-printing-torture-test',
    category: 'printer_tools',
    categoryTh: 'อัปเกรดเครื่องพิมพ์ 3D & อุปกรณ์ช่าง',
    categorySlug: 'printer_tools',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP', '.3MF'],
    fileSizeMb: 11.2,
    dimensionsCm: { width: 3.1, depth: 6.0, height: 4.8 },
    estimatedPrintHours: 1.0,
    estimatedWeightGrams: 14,
    recommendedMaterial: 'เรซิน 8K หรือ PLA สำหรับเทียบสเกลและทดสอบความแม่นยำ',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    description: 'The universally recognized 3D printer calibration test boat designed to challenge overhangs, bridges, and dimensional accuracy.',
    descriptionTh: 'โมเดลเรือทดสอบการคาลิเบรตเครื่องพิมพ์ 3D ที่ทุกคนในโลกต้องมี ใช้ทดสอบการยื่น Overhang สะพานเส้น และความคมชัดของมิติ',
    tags: ['Benchy', 'Calibration', 'Benchmark', 'Test', 'TortureTest', 'PrinterTool'],
    likesCount: 120000,
    downloadsCount: 850000,
    featured: true,
  },
  {
    id: 'stl-tool-02',
    title: 'Compact Hex Screwdriver & Allen Key Tool Holder',
    titleTh: 'แท่นเสียบชุดประแจหกเหลี่ยมและไขควงช่าง',
    creator: 'PrusaResearch',
    creatorUrl: 'https://www.printables.com/@Prusa3D',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com/model/22019-hex-key-caddy',
    downloadUrl: 'https://www.printables.com/model/22019-hex-key-caddy',
    directStlUrl: 'https://www.printables.com/model/22019-hex-key-caddy',
    category: 'printer_tools',
    categoryTh: 'อัปเกรดเครื่องพิมพ์ 3D & อุปกรณ์ช่าง',
    categorySlug: 'printer_tools',
    license: 'GPLv3',
    fileFormat: ['.STL', '.STEP'],
    fileSizeMb: 3.5,
    dimensionsCm: { width: 8.0, depth: 6.0, height: 7.5 },
    estimatedPrintHours: 2.5,
    estimatedWeightGrams: 55,
    recommendedMaterial: 'คาร์บอนไฟเบอร์ PETG ทนน้ำมันและสารเคมีช่าง',
    recommendedMaterialId: 'petg_carbon_fiber',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    description: 'Stepped organizer caddy for Allen keys from 1.5mm to 10mm with embossed sizing numbers.',
    descriptionTh: 'แท่นจัดเก็บประแจหกเหลี่ยมขนาด 1.5mm - 10mm สกรีนตัวเลขขนาดชัดเจน หยิบใช้งานสะดวกบนโต๊ะช่าง',
    tags: ['Tools', 'HexKey', 'Workshop', 'Organization', 'Organizer'],
    likesCount: 15000,
    downloadsCount: 58000,
  },
];
