export interface FreeSTLModel {
  id: string;
  title: string;
  titleTh: string;
  creator: string;
  source: 'Printables' | 'Thingiverse' | 'Thangs' | 'NASA 3D' | 'Smithsonian' | 'MakerWorld' | 'Scan The World';
  sourceUrl: string;
  downloadUrl: string;
  category: 'scifi' | 'fantasy' | 'art_statue' | 'functional' | 'home_decor' | 'engineering';
  categoryTh: string;
  license: 'CC BY 4.0' | 'CC0 Public Domain' | 'Creative Commons' | 'GPLv3';
  fileFormat: string[];
  dimensionsCm: { width: number; depth: number; height: number };
  estimatedPrintHours: number;
  recommendedMaterial: string;
  recommendedMaterialId: string;
  imageUrl: string;
  description: string;
  descriptionTh: string;
  tags: string[];
  shapePreset: 'cyberpunk_helmet' | 'dragon_sculpture' | 'roman_bust' | 'scifi_mech' | 'sacred_artifact' | 'voronoi_vase' | 'cute_mascot';
  featured?: boolean;
}

export interface STLRepository {
  name: string;
  nameTh: string;
  url: string;
  searchUrl: (query: string) => string;
  description: string;
  badge: string;
  itemCount: string;
  logoColor: string;
}

export const GLOBAL_STL_REPOSITORIES: STLRepository[] = [
  {
    name: 'Printables by Prusa',
    nameTh: 'Printables (โดย Prusa Research)',
    url: 'https://www.printables.com',
    searchUrl: (q) => `https://www.printables.com/search/models?q=${encodeURIComponent(q)}`,
    description: 'คลังไฟล์ STL คุณภาพสูงอันดับ 1 มีการทดสอบพิมพ์จริงและไฟล์ G-Code พร้อมใช้งาน',
    badge: 'คุณภาพสูงอันดับ 1',
    itemCount: '600,000+ โมเดล',
    logoColor: '#fa6838',
  },
  {
    name: 'MakerWorld by Bambu Lab',
    nameTh: 'MakerWorld (โดย Bambu Lab)',
    url: 'https://makerworld.com',
    searchUrl: (q) => `https://makerworld.com/en/search/models?keyword=${encodeURIComponent(q)}`,
    description: 'แพลตฟอร์ม STL ยอดนิยมใหม่ล่าสุด รวมโมเดล 3D หลายสีและของแต่งบ้านสุดโมเดิร์น',
    badge: 'กำลังมาแรงที่สุด',
    itemCount: '450,000+ โมเดล',
    logoColor: '#00ae42',
  },
  {
    name: 'Thingiverse',
    nameTh: 'Thingiverse (คลังโมเดลระดับตำนาน)',
    url: 'https://www.thingiverse.com',
    searchUrl: (q) => `https://www.thingiverse.com/search?q=${encodeURIComponent(q)}&page=1`,
    description: 'คลังโมเดล 3D ฟรีที่ใหญ่ที่สุดในโลก เปิดบริการยาวนานกว่า 15 ปี',
    badge: 'ใหญ่ที่สุดในโลก',
    itemCount: '2,500,000+ โมเดล',
    logoColor: '#248bfb',
  },
  {
    name: 'Thangs 3D',
    nameTh: 'Thangs 3D (เสิร์ชเอนจินโมเดล 3 มิติ)',
    url: 'https://thangs.com',
    searchUrl: (q) => `https://thangs.com/search/${encodeURIComponent(q)}?scope=all`,
    description: 'ค้นหาโมเดล 3D ข้ามทุกเว็บไซต์ทั่วโลกด้วยระบบค้นหารูปทรง Geometric Search',
    badge: 'เสิร์ชเอนจินทรงพลัง',
    itemCount: '15,000,000+ โมเดล',
    logoColor: '#8b5cf6',
  },
  {
    name: 'NASA 3D Resources',
    nameTh: 'NASA 3D (โมเดลอวกาศและดาวเทียมแท้)',
    url: 'https://nasa3d.arc.nasa.gov',
    searchUrl: (q) => `https://nasa3d.arc.nasa.gov/models`,
    description: 'โมเดลยานอวกาศ จรวด กล้องเจมส์เว็บบ์ และภูมิประเทศดวงจันทร์จากองค์การนาซา',
    badge: 'ลิขสิทธิ์ฟรี Public Domain',
    itemCount: '1,000+ โมเดลอวกาศ',
    logoColor: '#0b3d91',
  },
  {
    name: 'Scan The World (Smithsonian & Museums)',
    nameTh: 'Scan The World (สแกน 3D พิพิธภัณฑ์โลก)',
    url: 'https://www.myminifactory.com/scantheworld',
    searchUrl: (q) => `https://www.myminifactory.com/scantheworld/search?query=${encodeURIComponent(q)}`,
    description: 'งานประติมากรรมระดับโลก สแกน 3D ความละเอียดสูงจากพิพิธภัณฑ์ลูฟวร์และสมิธโซเนียน',
    badge: 'ประติมากรรมระดับโลก',
    itemCount: '25,000+ ชิ้นงานศิลปะ',
    logoColor: '#d97706',
  },
  {
    name: 'Yeggi 3D Search',
    nameTh: 'Yeggi (เครื่องมือค้นหาไฟล์ 3D ทั่วโลก)',
    url: 'https://www.yeggi.com',
    searchUrl: (q) => `https://www.yeggi.com/q/${encodeURIComponent(q)}/`,
    description: 'ดัชนีรวบรวมไฟล์ STL ฟรีจากเว็บไซต์ 3D ทั่วโลกมากกว่า 4.8 ล้านรายการ',
    badge: 'ค้นหาทั่วโลก',
    itemCount: '4,800,000+ ดัชนี',
    logoColor: '#0284c7',
  },
];

export const CURATED_FREE_STL_MODELS: FreeSTLModel[] = [
  {
    id: 'stl-oni-cyber-mask',
    title: 'Cyberpunk Oni Samurai Battle Mask',
    titleTh: 'หน้ากากซามูไรโอนิ ไซเบอร์พังค์ พร้อมเขี้ยวและช่องหายใจ',
    creator: 'Hex3D Design',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com',
    downloadUrl: 'https://www.printables.com',
    category: 'scifi',
    categoryTh: 'ไซไฟ & เมคา',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.OBJ', '.3MF'],
    dimensionsCm: { width: 14.5, depth: 12.0, height: 18.0 },
    estimatedPrintHours: 8.5,
    recommendedMaterial: '8K Ultra-Detail Resin (เรซินความละเอียดสูง 8K)',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    description: 'A menacing futuristic cyberpunk mask featuring modular horns, respirator filters, and wearable strap brackets.',
    descriptionTh: 'หน้ากากไซเบอร์พังค์สไตล์โอนิสุดเท่ มีเขาและระบบท่อระบายลม พร้อมสล็อตสำหรับใส่สายรัดสวมใส่ได้จริง',
    tags: ['cyberpunk', 'mask', 'cosplay', 'helmet', 'wearable', 'oni', 'samurai'],
    shapePreset: 'cyberpunk_helmet',
    featured: true,
  },
  {
    id: 'stl-celestial-dragon',
    title: 'Articulated Celestial Crystal Dragon',
    titleTh: 'มังกรสวรรค์คริสตัล ข้อต่อขยับได้ทุกชิ้นส่วน (Flexi Dragon)',
    creator: 'McGybeer Studios',
    source: 'MakerWorld',
    sourceUrl: 'https://makerworld.com',
    downloadUrl: 'https://makerworld.com',
    category: 'fantasy',
    categoryTh: 'แฟนตาซี & ฟิกเกอร์',
    license: 'Creative Commons',
    fileFormat: ['.STL', '.3MF'],
    dimensionsCm: { width: 16.0, depth: 14.0, height: 15.0 },
    estimatedPrintHours: 11.0,
    recommendedMaterial: 'Engineering Tough Carbon (คาร์บอนไฟเบอร์เหนียวพิเศษ)',
    recommendedMaterialId: 'engineering_tough',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    description: 'Print-in-place articulated dragon with intricate scales and fully flexible interlocking joints requiring no assembly.',
    descriptionTh: 'โมเดลมังกรแฟนตาซียอดนิยมอันดับ 1 ของโลก พิมพ์เสร็จขยับเลื้อยได้ทันที ไม่ต้องประกอบชิ้นส่วน',
    tags: ['dragon', 'articulated', 'flexi', 'fantasy', 'print_in_place', 'toy', 'creature'],
    shapePreset: 'dragon_sculpture',
    featured: true,
  },
  {
    id: 'stl-marcus-aurelius-bust',
    title: 'Emperor Marcus Aurelius Classical Bronze Bust',
    titleTh: 'รูปปั้นครึ่งตัวจักรพรรดิโรมัน มาร์คุส ออเรลิอุส (สแกนพิพิธภัณฑ์)',
    creator: 'Scan The World / Louvre Museum',
    source: 'Smithsonian',
    sourceUrl: 'https://www.myminifactory.com/scantheworld',
    downloadUrl: 'https://www.myminifactory.com/scantheworld',
    category: 'art_statue',
    categoryTh: 'ศิลปะ & ประติมากรรม',
    license: 'CC0 Public Domain',
    fileFormat: ['.STL', '.OBJ'],
    dimensionsCm: { width: 13.0, depth: 11.0, height: 19.5 },
    estimatedPrintHours: 9.0,
    recommendedMaterial: 'Lost-Wax Cast Bronze (ทองสัมฤทธิ์หล่อโบราณแท้)',
    recommendedMaterialId: 'cast_bronze',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    description: 'Ultra high-definition photogrammetry 3D scan of the classical Roman philosopher emperor sculpture from the Louvre Museum.',
    descriptionTh: 'ไฟล์ 3D สแกนแท้จากพิพิธภัณฑ์ เก็บรายละเอียดใบหน้า เครา และเสื้อคลุมโรมันได้อย่างคมชัดสมบูรณ์แบบ',
    tags: ['roman', 'statue', 'sculpture', 'bust', 'museum', 'art', 'philosophy', 'history'],
    shapePreset: 'roman_bust',
    featured: true,
  },
  {
    id: 'stl-heavy-mech-titan',
    title: 'Titan Vanguard Heavy Assault Mech',
    titleTh: 'หุ่นยนต์รบเมคาไททัน เกราะหนักพร้อมอาวุธปืนใหญ่',
    creator: 'Aether Mechworks',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com',
    downloadUrl: 'https://www.printables.com',
    category: 'scifi',
    categoryTh: 'ไซไฟ & เมคา',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP', '.3MF'],
    dimensionsCm: { width: 14.0, depth: 12.0, height: 18.5 },
    estimatedPrintHours: 12.5,
    recommendedMaterial: '8K Ultra-Detail Resin (เรซินความละเอียดสูง 8K)',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    description: 'Detailed modular sci-fi mecha with poseable ball joints, heavy armor plates, and dual shoulder cannons.',
    descriptionTh: 'หุ่นยนต์ไซไฟเกราะหนา รายละเอียดกลไกแน่น เหมาะสำหรับลงสีฟิกเกอร์และตั้งโชว์บนโต๊ะทำงาน',
    tags: ['mech', 'robot', 'gundam', 'scifi', 'armor', 'titan', 'miniature'],
    shapePreset: 'scifi_mech',
  },
  {
    id: 'stl-voronoi-spiral-vase',
    title: 'Parametric Voronoi Twisted Spiral Vase',
    titleTh: 'แจกันศิลปะเกลียว Voronoi พารามิเตอร์ ดีไซน์โมเดิร์น',
    creator: 'Studio Parametrica',
    source: 'Thingiverse',
    sourceUrl: 'https://www.thingiverse.com',
    downloadUrl: 'https://www.thingiverse.com',
    category: 'home_decor',
    categoryTh: 'ของแต่งบ้าน & แจกัน',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.3MF'],
    dimensionsCm: { width: 11.0, depth: 11.0, height: 20.0 },
    estimatedPrintHours: 6.5,
    recommendedMaterial: 'Transparent Optical Crystal Resin (เรซินใสออพติคอล)',
    recommendedMaterialId: 'transparent_resin',
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    description: 'Sculptural organic spiral vase with intricate Voronoi mesh network optimized for beautiful light reflections.',
    descriptionTh: 'แจกันทรงเกลียวโครงข่ายออร์แกนิก ลวดลายพลิ้วไหวโปร่งแสง ช่วยสร้างความสวยงามและสะท้อนแสงได้อย่างมีมิติ',
    tags: ['vase', 'voronoi', 'home_decor', 'spiral', 'abstract', 'flower_pot', 'interior'],
    shapePreset: 'voronoi_vase',
  },
  {
    id: 'stl-nasa-james-webb',
    title: 'NASA James Webb Space Telescope Scale Model',
    titleTh: 'โมเดลกล้องโทรทรรศน์อวกาศเจมส์เว็บบ์ (NASA JWST แท้)',
    creator: 'NASA Goddard Space Flight Center',
    source: 'NASA 3D',
    sourceUrl: 'https://nasa3d.arc.nasa.gov',
    downloadUrl: 'https://nasa3d.arc.nasa.gov',
    category: 'engineering',
    categoryTh: 'วิศวกรรม & อวกาศ',
    license: 'CC0 Public Domain',
    fileFormat: ['.STL', '.OBJ', '.GLB'],
    dimensionsCm: { width: 15.0, depth: 12.5, height: 16.0 },
    estimatedPrintHours: 7.5,
    recommendedMaterial: '8K Ultra-Detail Resin (เรซินความละเอียดสูง 8K)',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=800&q=80',
    description: 'Official NASA engineering 3D model of the JWST gold hexagonal primary mirror and sunshield layers.',
    descriptionTh: 'ไฟล์ 3D ทางการจากองค์การนาซา แสดงกระจกหกเหลี่ยมสีทองและแผงกันความร้อนของกล้องโทรทรรศน์อวกาศ',
    tags: ['nasa', 'space', 'telescope', 'jwst', 'engineering', 'satellite', 'astronomy'],
    shapePreset: 'sacred_artifact',
  },
  {
    id: 'stl-cute-cyber-fox',
    title: 'Chibi Mechanical Cyber Fox Mascot',
    titleTh: 'มาสคอตจิ้งจอกไซเบอร์ตัวจิ๋ว (Chibi Mech Fox)',
    creator: 'AnimeForge 3D',
    source: 'Printables',
    sourceUrl: 'https://www.printables.com',
    downloadUrl: 'https://www.printables.com',
    category: 'fantasy',
    categoryTh: 'แฟนตาซี & ฟิกเกอร์',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.OBJ'],
    dimensionsCm: { width: 10.5, depth: 10.0, height: 14.0 },
    estimatedPrintHours: 5.5,
    recommendedMaterial: '8K Ultra-Detail Resin (เรซินความละเอียดสูง 8K)',
    recommendedMaterialId: 'sla_ultra_resin',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    description: 'Adorable chibi stylized robotic fox figurine with expressive eyes, oversized ears, and headset details.',
    descriptionTh: 'ฟิกเกอร์สไตล์อนิเมะตัวกลมป้อม หูใหญ่สวมหูฟังเมคานิกส์ ออกแบบมาให้พิมพ์ง่าย ลบซัพพอร์ตได้สะอาด',
    tags: ['fox', 'chibi', 'anime', 'cute', 'mascot', 'toy', 'figure'],
    shapePreset: 'cute_mascot',
  },
  {
    id: 'stl-phone-stand-gear',
    title: 'Universal Geared Foldable Phone & Tablet Stand',
    titleTh: 'แท่นวางมือถือและแท็บเล็ต ระบบฟันเฟืองพับเก็บได้',
    creator: 'Enginix Tools',
    source: 'Thingiverse',
    sourceUrl: 'https://www.thingiverse.com',
    downloadUrl: 'https://www.thingiverse.com',
    category: 'functional',
    categoryTh: 'ของใช้ & อุปกรณ์เครื่องมือ',
    license: 'CC BY 4.0',
    fileFormat: ['.STL', '.STEP'],
    dimensionsCm: { width: 9.0, depth: 12.0, height: 13.0 },
    estimatedPrintHours: 4.5,
    recommendedMaterial: 'Engineering Tough Carbon (คาร์บอนไฟเบอร์เหนียวพิเศษ)',
    recommendedMaterialId: 'engineering_tough',
    imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=800&q=80',
    description: 'Fully adjustable desktop mobile and iPad stand featuring multi-angle locking gears and non-slip grooves.',
    descriptionTh: 'อุปกรณ์เครื่องมืออเนกประสงค์ ปรับระดับมุมมองได้หลายองศา แข็งแรง ทนทาน และพับพกพาได้',
    tags: ['phone_stand', 'functional', 'gadget', 'desk', 'gear', 'tools', 'tablet'],
    shapePreset: 'sacred_artifact',
  },
];
